"""Added account table

Revision ID: a9a001161838
Revises: 43f79daff0cd
Create Date: 2022-05-06 11:00:07.312044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9a001161838'
down_revision = '43f79daff0cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chip_id', sa.Integer(), nullable=False),
    sa.Column('mac_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('smartclass',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('classroom', sa.String(), nullable=False),
    sa.Column('power_consumption', sa.Float(), nullable=False),
    sa.Column('Switchstatus', sa.Boolean(), server_default='False', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('smartpole',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('polename', sa.String(), nullable=False),
    sa.Column('Temperature', sa.Float(), nullable=False),
    sa.Column('Humidity', sa.Float(), nullable=False),
    sa.Column('Air_quality', sa.Float(), nullable=False),
    sa.Column('Co2_emission', sa.Float(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('smartpole')
    op.drop_table('smartclass')
    op.drop_table('Devices')
    # ### end Alembic commands ###
